name: ollama
services:
    ollama:
        build:
            context: ./docker  # Adjust if your Dockerfile is inside a "docker" folder
        container_name: ollama
        restart: unless-stopped
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama

volumes:
    ollama_data:
